# Site Information
site_name: "CPU Cycles Comparison: Multiple-If vs Switch-Case"

# Theme Configuration
theme:
  name: material  # Material for MkDocs theme
  palette:
    scheme:  default
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Fira Codez

# Navigation Structure
nav:
  - Home: index.md
  - Introduction: introduction.md
  - What is CPU?: what_is_cpu.md
  - Why Do CPU Cycles Matter?: why_cpu_cycles_matter.md
  - Multiple-If Statements:
      - What Are Multiple-If Statements?: multiple_if/what_is_multiple_if.md
      - Example of Multiple-If in Python: multiple_if/example_multiple_if.md
      - CPU Cycles in Multiple-If: multiple_if/cpu_cycles_multiple_if.md
      - Pros of Multiple-If: multiple_if/pros_multiple_if.md
      - Cons of Multiple-If: multiple_if/cons_multiple_if.md
  - Switch-Case:
      - What Is Switch-Case?: switch_case/what_is_switch_case.md
      - Example of Switch-Case in Python: switch_case/example_switch_case.md
      - CPU Cycles in Switch-Case: switch_case/cpu_cycles_switch_case.md
      - Pros of Switch-Case: switch_case/pros_switch_case.md
      - Cons of Switch-Case: switch_case/cons_switch_case.md
  - CPU Cycles Comparison: cpu_cycles_comparison.md
  - When to Use Multiple-If: when_to_use_multiple_if.md
  - When to Use Switch-Case: when_to_use_switch_case.md
  - Conclusion: conclusion.md


# Markdown Extensions
markdown_extensions:
  - admonition  # Adds note, tip, and warning blocks
  - codehilite:  # Adds code highlighting
      linenums: true  # Optional: adds line numbers to code blocks
  - toc:
      permalink: true  # Adds anchors to headings for easy navigation
  - pymdownx.highlight  # Improves code highlighting
